// <auto-generated />
using System;
using Klinika_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klinika_backend.Migrations
{
    [DbContext(typeof(APP_DB_Context))]
    partial class APP_DB_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Klinika_backend.Models.Lekar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lekar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "271a57cf-fc20-42ac-90de-54095c959f31",
                            ConcurrencyStamp = "271a57cf-fc20-42ac-90de-54095c959f31",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "eca0f843-7b9b-4cbe-8701-3db7ccae7411",
                            ConcurrencyStamp = "eca0f843-7b9b-4cbe-8701-3db7ccae7411",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "b638bc65-51e5-4c4e-9519-78e34c6293d5",
                            ConcurrencyStamp = "b638bc65-51e5-4c4e-9519-78e34c6293d5",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
